### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by jb123567** [MelleD/robovac#1]
Not sure if you are now taking this repo further? I seem to be getting this error with the L60, any thoughts?

```

Logger: homeassistant.components.vacuum
Source: helpers/entity_platform.py:360 
Integration: Vacuum (documentation, issues) 
First occurred: 21:16:09 (2 occurrences) 
Last logged: 21:18:55

Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/robovac/vacuum.py", line 128, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 296, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'

```

**Comment by MelleD** [comment]
Hey @jb123567,

please add you issue to your repo here: https://github.com/CodeFoodPixels/robovac

I just try to fix some issue for my vacuum and add PRs
